server:
  port: 8368
  max-http-header-size: 20480000

spring:
  datasource:
    url: jdbc:mysql://121.37.39.206:3306/modeling?characterEncoding=utf-8
    username: modeling
    password: Zrx@20041009
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 200MB
  redis:
    host: localhost
    port: 6379
    password: Zrx@20041009
    database: 10
mybatis-plus:
  global-config:
    banner: false
    enable-sql-runner: true
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: DELETE_FLAG
      logic-delete-value: DELETED
      logic-not-delete-value: NOT_DELETE
  mapper-locations: classpath*:com/test/**/mapping/*.xml,com/bstek/**/mapping/*.xml
  type-handlers-package: com.test.common.handler
  pagination:
    type: OFFSET




